FROM rust:1.78.0-slim as builder
WORKDIR /usr/src/block_chat
COPY ./ ./
RUN cargo build --release

FROM rust:1.78.0-slim
WORKDIR /usr/src/block_chat
COPY ./test_inputs ./test_inputs
COPY --from=builder /usr/src/block_chat/target/release/helper /usr/local/bin/helper
CMD [ "helper" ]
